#rodar o comando docker-compose up para rodar o banco
#se rodar docker-compose up -d ira rodar em backgroud
version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - "3306:3306"
    volumes:
    - jsouza_data:/var/lib/mysql

volumes:
  jsouza_data:
